### ISSUE TITLE
Simplify selection

### ISSUE THREAD

**Issue by sholderbach** [datascience-mobi/2021-topic-01-team-01#2]
It is somewhat dangerous to have manually entered sets of indices to select items. As you determined these indices by running the `which()` function, you can simply save those in a variable and reuse that to select wherever you need that exact selection. This will work even if the input `data.frame` would change. 

https://github.com/datascience-mobi/2021-topic-01-team-01/blob/54e65f2a065bd6880cb35bb5f80205c1603bed3e/topic_1_disulfiram/topic_1_linear_regression.Rmd#L22-L35

Additionally it seems you are trying  to do these steps to align two dataframes to have exactly corresponding columns for your regression. This could also be achieved by using the `merge()` or `dplyr::inner_join()` functions to create a `data.frame` where all rows with matching names are aligned containing the required columns from both. Otherwise you might run into trouble if the order of rows is not exactly the same.

**Comment by LenaWickenhaeuser** [comment]
Can you check my approach with both methods in the updated document? There are some problems using the named functions and I can't continue without solving them. I already talked about it with Moritz but we had no idea how to modify the functions to gain the desired results.

**Comment by sholderbach** [comment]
Both `inner_join` and `merge` operate only/best on `data.frame`s. So the strategy would be to first select the range of columns you need (all relevant genes; all drug sensitivities.) Then, for the `inner_join` function you have to add the `rownames` as a named column as `dplyr` prefers to work with all information in columns. Those two data.frames you then can join using the `by` parameter set to the `cellline_id` column name (containing the unique rownames).

**Comment by LenaWickenhaeuser** [comment]
Thanks for your help. I think I fixed it but now, the problem ist that the order of the row names in Prism and Prism.exp are not the same so its worthless to join the data frames without the right values to the corresponding cell lines. I already tried to use the arrange() and order() functions but the wrong order stayed so there is no change in output. It seems like those functions only work properly with numeric values. Do you have any idea how to solve that?

**Comment by sholderbach** [comment]
I am unsure about the last part. But the join functions should reorder entries if necessary based on the columns given in the `by` parameter. Could you highlight/post a code snippet?

**Comment by LenaWickenhaeuser** [comment]
https://github.com/datascience-mobi/2021-topic-01-team-01/blob/28be1059f94fdaaf283616601867163314577f5e/topic_1_disulfiram/topic_1_linear_regression.Rmd#L47-L60

Here you can see my code, I already checked whether the join function reorders the rows and its entries of Prism.exp.dgenes according to the order of the join.cells column but that's not the case.
How can I modify the given code or which other function can I use to fix the ordering problem?

**Comment by sholderbach** [comment]
`cbind()` should be binding on current order in memory, so if you assign the same column to both the disjoint data frames this will run into trouble. If you import dplyr anyways you can use the `mutate()` function on each data frame to create the `celline_id` column (try to be explicit with variable names what it actually contains)

``` R
Zprism.exp.dgenes <- mutate(Zprism.exp.dgenes, cellline_id = rownames(Zprism.exp.dgenes)) 
disulfiram.prism.expgenes <- mutate(disulfiram.prism.expgenes, cellline_id = rownames(disulfiram.prism.expgenes))

LRM.df = dplyr::inner_join(Zprism.exp.dgenes, disulfiram.prism.expgenes, by = "cellline_id")
```

**Comment by sholderbach** [comment]
Also with `inner_join` or the `semi_join` variation the whole ids %in% other ids logic won't be necessary.

Datacamp suggestion: https://learn.datacamp.com/courses/joining-data-with-dplyr

**Comment by LenaWickenhaeuser** [comment]
It looks like it works now. Thank you so much for your time and your great help! I hope the linear regression model can be coded without any further problems now.
